### ISSUE TITLE
程序包com.gn.decorator不存在

### ISSUE THREAD

**Issue by lin1005q** [realpdai/springboot-javafx-app-demo#1]

**Comment by jer2015** [comment]
手动加入lib依赖

**Comment by yokim321** [comment]
com.gn.decorator  这个程序包在哪里下载

**Comment by realpdai** [comment]
不好意思很久没看这个项目。

除了手动添加依赖的jar之外，还可以maven install到本地的仓库，具体可以参考编译和部署部分的文档 [部署文档](https://github.com/realpdai/springboot-javafx-app-demo#%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2)
