### ISSUE TITLE
求教，如何打包

### ISSUE THREAD

**Issue by jinn520** [realpdai/springboot-javafx-app-demo#6]
用maven的方式打包之后，运行什么反应都没有，就像运行了空气一样

**Comment by realpdai** [comment]
不好意思很久没看这个项目。

更新了下编译和部署部分的文档 [部署文档](https://github.com/realpdai/springboot-javafx-app-demo#%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2)

**Comment by liujin2205** [comment]
您好，解决了嘛
