### ISSUE TITLE
Dependencies Error

### ISSUE THREAD

**Issue by MehmetNuri** [realpdai/springboot-javafx-app-demo#8]
````Cannot resolve gn:GNAvatarView:v1.0-rc

Cannot resolve gn:GNCarousel:v2.1.5

Cannot resolve gn:GNButton:v1.1.0

Cannot resolve gn:GNCalendar:v1.0

Cannot resolve gn:GNDecorator:v2.1.2-alpha
````

**Comment by Ggbr-TaoLi** [comment]
lib里有jar包，可以在pom.xml里进行本地引入：
<dependency>
			<groupId>com.gn.decorator</groupId>
			<artifactId>com-lib</artifactId>
			<version>2.1.2</version>
			<scope>system</scope>
			<systemPath>${pom.basedir}/lib/GNDecorator-2.1.2-alpha.jar</systemPath>
</dependency>

**Comment by Ggbr-TaoLi** [comment]
lib里有jar包，可以在pom.xml里进行本地引入：
`	<dependency>
			<groupId>com.gn.decorator</groupId>
			<artifactId>com-lib</artifactId>
			<version>2.1.2</version>
			<scope>system</scope>
			<systemPath>${pom.basedir}/lib/GNDecorator-2.1.2-alpha.jar</systemPath>
		</dependency>`
